import type { Metadata } from "next";
import { Poppins, Inter, Edu_NSW_ACT_Foundation } from "next/font/google";

// STYLE SHEETS SOURCE
import "../styles/globals.css";
import Header from "@/containers/home-page/header";
import Footer from "@/containers/home-page/footer";

// FONT CONFIGURATIONS (do NOT export)
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const eduHand = Edu_NSW_ACT_Foundation({
  subsets: ["latin"],
  variable: "--font-edu-hand",
  display: "swap",
  weight: ["400", "500", "700"],
  style: ["normal"],
});

// METADATA export is fine
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} ${eduHand.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
