import type { Metadata } from "next";
import { Poppins, Inter, Edu_NSW_ACT_Foundation } from "next/font/google";

// STYLE SHEETS SOURCE
import "@/styles/globals.css";

// FONT CONFIGURATIONS
export const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const eduHand = Edu_NSW_ACT_Foundation({
  subsets: ["latin"],
  variable: "--font-edu-hand",
  display: "swap",
  weight: ["400", "500", "700"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} ${eduHand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
